branches:
  only:
  - master
services:
- docker
script:
- make test || exit 1
after_success:
- |
  [ "${TRAVIS_BRANCH}" == "master" ] &&
    (docker login --username $DOCKER_USER --password $DOCKER_PASS; \
    make release)
notifications:
  slack:
    secure: jdnG7+3rlurbBYijZBMJ0vdQ//riBaYTvpHXV5ZxHWS8opruxa9Bi2OHYd/C5SHs8Zpe0jV3Xz4F1bUFNiZYO+RKnCl54ZZ2x6haPx3+TfEp7bRcMmlAiCOOqxhdJ4+baNTvLz/xS+RzSLB2gUrUhlk6h5fXrkkqmvfBDasKqNLFyKR1d0cYyeC0sb2M5kW2K08NwCnWa32lXPPcbr7ENgT6aZ7QpkoqsfxO7kyy4GY0C2Pd9beSjFU8jAyDSWKahye+GseJu1J9/hvX/038NIPIIwAvRDhpM0Fi9JBUT3CICeYfuxbLUvDrebMLAEUYQnwpv4OGbiCS9idC2cHlENK9CHiQYo/QAeVruLlpniVmBqHqlHM3dgOpOE3MMKG2emFhBHkYq6b0lberLJiWdXgltQOboxekg8zC/iSi1PpZpP7oS9twziVMIUJp8UqHLH8mF09yjQ2gAvcWCqG4E9rnqUQdW+7N4RKcYUvunj4zwUwBK1+h2/rMm/x+Y6jrOECXTLvuH20IiKZoTjWbZ9hpDUlKuQ3Lh0IGro/WSuu8KqdvJyyaiLLbyG3MNFpzL4Vj3l73/8hGrYPxvHQKIvbj756nodQ00/aOAvUFZPVFUdgx5m8LmFcsAevmK4sl1C9Oz3VqLUIV+5E4GbVLmI/1OudV+8zDBetMealiHDk=
